// flow-typed signature: b3e3e6c54f13ebdc988612485e9f0b4a
// flow-typed version: <<STUB>>/react-native-contacts_v1.0.0/flow_v0.57.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-contacts'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-contacts' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'react-native-contacts/index' {
  declare module.exports: $Exports<'react-native-contacts'>;
}
declare module 'react-native-contacts/index.js' {
  declare module.exports: $Exports<'react-native-contacts'>;
}
