// flow-typed signature: 9710c8618b4686154d3a91b823640bd7
// flow-typed version: <<STUB>>/react-native-contacts-wrapper_vhttps://github.com/gevorg94/react-native-contacts-wrapper.git/flow_v0.57.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-contacts-wrapper'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-contacts-wrapper' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'react-native-contacts-wrapper/index' {
  declare module.exports: $Exports<'react-native-contacts-wrapper'>;
}
declare module 'react-native-contacts-wrapper/index.js' {
  declare module.exports: $Exports<'react-native-contacts-wrapper'>;
}
