//
//  AppDelegate.swift
//  LetsChat
//
//  Created by Simply Technologies on 12/14/17.
//  Copyright © 2017 Facebook. All rights reserved.
//

import UIKit
import FirebaseCore

@UIApplicationMain
class AppDelegate: UIResponder, UIApplicationDelegate {

  var window: UIWindow?

  func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplicationLaunchOptionsKey : Any]? = nil) -> Bool {

    FirebaseApp.configure()

    var jsCodeLocation: URL?
    #if DEBUG
//      uncomment the next line for running on real device (set correct ip address)
      jsCodeLocation = NSURL(string:"http://192.168.2.46:8081/index.bundle?platform=ios&dev=true") as URL?
//      jsCodeLocation = RCTBundleURLProvider.sharedSettings().jsBundleURL(forBundleRoot: "index", fallbackResource: nil)
    #else
      jsCodeLocation = Bundle.main.url(forResource: "main", withExtension: "jsbundle")
    #endif
    print("---------------- AppDelegate: LOOKING FOR JS IN :",jsCodeLocation!," --------------------")
    /**
     * OPTION 2
     * Load from pre-bundled file on disk. The static bundle is automatically
     * generated by the "Bundle React Native code and images" build step when
     * running the project on an actual device or running the project on the
     * simulator in the "Release" build configuration.
     */

    self.window = UIWindow(frame: UIScreen.main.bounds)
    self.window?.backgroundColor = UIColor.white
    RCCManager.sharedInstance().initBridge(withBundleURL: jsCodeLocation!, launchOptions: launchOptions)

    return true
  }
}
